#!/usr/bin/env node
// Bakes PKG_VERSION at build time into src/core/version.ts.
//
// Why: src/core/render.ts previously did `readFileSync(package.json)` at
// module-load. Under Next.js bundling in clud-bug-app (App-side consumer),
// `import.meta.url` resolves to `.next/server/...` not the node_modules
// layout, so the file lookup throws ENOENT. PR #50 worked around this with
// `serverExternalPackages: ['clud-bug']` in next.config.js. This script is
// the proper fix on the npm side — codegen the version at build time so
// no consumer needs the workaround.
//
// Wired via "prebuild" in package.json so every `npm run build` (and
// `npm pack`, which runs prepublishOnly → build) regenerates it.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(__dirname, '..', 'package.json');
const outPath = join(__dirname, '..', 'src', 'core', 'version.ts');

const { version } = JSON.parse(readFileSync(pkgPath, 'utf8'));

const contents = `// Generated by scripts/gen-version.mjs at build time. Do not edit.
// Regenerated automatically on every \`npm run build\` via "prebuild" hook.
export const PKG_VERSION = '${version}';
`;

writeFileSync(outPath, contents);
console.log(`gen-version: wrote src/core/version.ts with PKG_VERSION='${version}'`);
